export const GET_CHARACTERS_SUCCEEDED = "GET_CHARACTERS_SUCCEEDED";
export const GET_CHARACTERS_FAILED = "GET_CHARACTERS_FAILED";
export const GET_CHARACTER_DETAIL_SUCCEEDED = "GET_CHARACTER_DETAIL_SUCCEEDED";
export const GET_CHARACTER_DETAIL_FAILED = "GET_CHARACTER_DETAIL_FAILED";
export const GET_CHARACTER_COMICS_SUCCEEDED = "GET_CHARACTER_COMICS_SUCCEEDED";
export const GET_CHARACTER_COMICS_FAILED = "GET_CHARACTER_COMICS_FAILED";
